services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cocktaildle_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cocktaildle
      - JWT_SECRET=secret_key
    depends_on:
      postgres:
       condition: service_healthy

  postgres:
    image: postgres:15
    container_name: cocktaildle_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cocktaildle
    healthcheck:
      test: >
        pg_isready
        -U postgres
        -d postgres
        -h localhost
        -p 5432
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
